services:
    router-agent:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: router-agent
        restart: unless-stopped
        ports:
            - "3000:3000"
        environment:
            SEED_PHRASE: "agent's wallet seed phrase"
            BLOCKFROST_KEY: "blockfrost api key"
            KUPO_URL: "http://kupo:1442"
            OGMIOS_URL: "http://ogmios:1337"
        command: ["tail", "-f", "/dev/null"]
        tty: true
        stdin_open: true
        logging:
            driver: "json-file"
            options:
                max-size: "400k"
                max-file: "20"
        depends_on:
            - cardano-node
            - ogmios
            - kupo

    cardano-node:
        image: ghcr.io/blinklabs-io/cardano-node:10.4.1-3
        container_name: cardano-node
        restart: unless-stopped
        ports:
            - "3001:3001"
        volumes:
            - node-db:/data
            - node-ipc:/ipc
            - node-config:/opt/cardano/config
        environment:
            NETWORK: "preprod"
        logging:
            driver: "json-file"
            options:
                max-size: "400k"
                max-file: "20"

    ogmios:
        image: cardanosolutions/ogmios:v6.12.0
        container_name: ogmios
        restart: unless-stopped
        ports:
            - "1337:1337"
        volumes:
            - node-config:/config/cardano-node
            - node-ipc:/ipc
        environment:
            NETWORK: "preprod"
        command:
            [
                "--host",
                "0.0.0.0",
                "--node-socket",
                "/ipc/node.socket",
                "--node-config",
                "/config/cardano-node/preprod/config.json",
            ]
        logging:
            driver: "json-file"
            options:
                max-size: "400k"
                max-file: "20"
        depends_on:
            - cardano-node

    kupo:
        image: cardanosolutions/kupo:v2.10.0
        container_name: kupo
        restart: unless-stopped
        ports:
            - "1442:1442"
        volumes:
            - kupo-db:/db
            - node-ipc:/ipc
            - node-config:/config/cardano-node
        environment:
            NETWORK: "preprod"
        command:
            [
                "--host",
                "0.0.0.0",
                "--port",
                "1442",
                "--since",
                "origin",
                "--match",
                "*",
                "--node-config",
                "/config/cardano-node/preprod/config.json",
                "--node-socket",
                "/ipc/node.socket",
                "--workdir",
                "/db",
            ]
        logging:
            driver: "json-file"
            options:
                max-size: "400k"
                max-file: "20"
        depends_on:
            - cardano-node

volumes:
    node-db:
    node-ipc:
    node-config:
    kupo-db:
